config/routes.rb
Rails.application.routes.draw do

  # Add for devise
  devise_for :users

  namespace :admin do
    resources :trains do
      resource :carriages, shallow: true
    end
    resources :railway_stations do
      patch :update_position, on: :member
    end
    resources :routes
    resources :carriages
    resources :tickets
  end

  resources :tickets
  resource :search, only: [:show, :create]


  get 'welcome/index'
  #root 'welcome#index'

  get  'searches/index'
  root 'searches#show'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :trains
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes

  validates :title, presence: true
  validate  :station_count

  before_validation :set_title


  private

  def set_title
    self.title = "#{railway_stations.first.title} - #{railway_stations.last.title}" unless self.title.present?
  end


  def station_count
    if railway_stations.size < 2
      errors.add(:base, "Ошибка!  Маршрут должен содержать минимум две станции!")
    end
  end

end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(train_route_params)
    if @route.save
      redirect_to admin_route_path(@route)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @route.update(train_route_params)
      # redirect_to admin_route_path(@route)
      redirect_to admin_routes_path(@route)
    else
      render :new
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def train_route_params
    params.require(:route).permit(:title, railway_station_ids: [], train_ids: [])
  end

end

app/views/admin/routes/_form.html.erb
<%= form_for [:admin, route] do |f| %>
    <%= render 'common/errors', resource: route %>
    <div class="field">
      <%= f.label 'Наименование' %>
      <%= f.text_field :title%>
    </div>
    <div class="field">
      <%= f.label :railway_station_ids, "Cтанции:" %>
      <%= f.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, {multiple: true} %>
    </div>
    <div class="field">
      <%= f.label :train_ids, "Поезда:" %>
      <%= f.collection_select :train_ids, Train.all, :id, :number, {}, {multiple: true} %>
    </div>
    <div class="actions">
      <%= f.submit "#{route.new_record? ? 'Создать' : 'Изменить'}", class: 'btn btn-success' %>
    </div>
<% end %>

app/views/admin/routes/_inline_edit_form.html.erb
<%= form_for [:admin, route], html: { style: "display: #{hidden ? 'none' : 'block'}"} do |f| %>
    <%= render 'common/errors', resource: route %>

    <div class="field">
      <%= f.label 'Наименование' %>
      <%= f.text_field :title%>
    </div>

    <div class="actions">
      <%= f.submit "#{route.new_record? ? 'Создать' : 'Изменить'}", class: 'btn btn-success' %>
    </div>

<% end %>

app/views/admin/routes/_route.html.erb
<table class="table table-striped">
  <tr>
    <td>
      <div id="route_title_<%=route.id%>">
        <%= route.title %>
      </div>
      <%= render 'inline_edit_form', route: route, hidden: true %>
    </td>
    <td><%= link_to 'Показать', admin_route_path(route), class: 'btn btn-link' %></td>
    <td><%= link_to 'Редактировать', '', class: 'btn btn-link edit-route-name', data: {route_id: route.id} %></td>
    <td><%= link_to 'Удалить', admin_route_path(route), method: :delete, data: {confirm: 'Вы уверены?'}, class: 'btn btn-link' %></td>
  </tr>
</table>

app/views/admin/routes/edit.html.erb
<h1>Редактирование (маршрут)</h1>
<%= render 'form', route: @route %>
<%= link_to 'Показать', admin_route_path(@route), class: 'btn btn-link'  %> |
<%= link_to 'Назад', admin_route_path, class: 'btn btn-link'  %>

app/views/admin/routes/index.html.erb
<h1>Маршруты</h1>
<table>
  <thead>
  <tr>
    <th>Наименование</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <%= render @routes %>
  </tbody>
</table>
<br>
<%= link_to 'Новый маршрут', new_admin_route_path, class: 'btn btn-link' %>

app/views/admin/routes/new.html.erb
<h1>Добавить маршрут</h1>
<%= render 'form' , route: @route %>
<%= link_to 'Назад', admin_routes_path %>

app/views/admin/routes/show.html.erb
<p class="form-control">
  <strong>Наименование маршрута:</strong>
  <%= @route.title%>
</p>

<p class="form-control">
  <strong>Список поездов маршрута:</strong>
  <% if @route.trains.empty? %>
      Поездов на маршруте нет
  <% else %>
    <ul>
      <% @route.trains.each do |t| %>
          <li> <%= t.number %> </li>
      <% end %>
    </ul>
  <% end %>
</p>

<p class="form-control">
  <strong>Список станций маршрута:</strong>
  <% if @route.railway_stations.empty? %>
      Станций в маршруте нет
  <% else %>
    <table>
      <thead>
      <tr>
        <td width="100">Название</td>
        <td>Позиция</td>
      </tr>
      </thead>
      <tbody>
      <% @route.railway_stations.ordered.each do |s| %>
          <tr>
            <td> <%= s.title %> </td>
            <td>
              <%= form_tag update_position_admin_railway_station_path(s), method: :patch do %>
                  <%= number_field_tag :station_number, s.position_in(@route) %>
                  <%= hidden_field_tag :route_id, @route.id%>
                  <%= submit_tag "Изменить", class: 'btn btn-success' %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>
</p>

<%= link_to 'Редактировать', edit_admin_route_path(@route), class: 'btn btn-link' %> |
<%= link_to 'Назад', admin_routes_path, class: 'btn btn-link' %>