config/routes.rb
Rails.application.routes.draw do

  # Add for devise
  devise_for :users

  namespace :admin do
    resources :trains do
      resource :carriages, shallow: true
    end
    resources :railway_stations do
      patch :update_position, on: :member
    end
    resources :routes
    resources :carriages
    resources :tickets
  end

  resources :tickets
  resource :search, only: [:show, :create]


  get 'welcome/index'
  #root 'welcome#index'

  get  'searches/index'
  root 'searches#show'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train_route.rb
class TrainRoute < ApplicationRecord
  validates :title, presence:  true
end

app/views/train_routes/edit.html.erb
<h1>Редактировать маршрут</h1>

<%= form_for(@train_route) do |f| %>
    <% if @train_route.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@train_route.errors.count, "error") %> prohibited this railway_station from being saved:</h2>

          <ul>
            <% @train_route.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="actions">
      <%= f.submit 'Изменить' %>
    </div>
<% end %>


<%= link_to 'Показать', @train_routes %> |
<%= link_to 'Назад', train_route_path %>

app/views/train_routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Маршруты</h1>

<table>
  <thead>
  <tr>
    <th>Идентификатор</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @train_routes.each do |train_route| %>
      <tr>
        <td><%= train_route.title %></td>
        <td><%= link_to 'Показать', train_route %></td>
        <td><%= link_to 'Редактировать', edit_train_route_path(train_route) %></td>
        <td><%= link_to 'Удалить', train_route, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новый маршрут', new_train_route_path %>
<%= link_to 'Домой', welcome_index_path %>

app/views/train_routes/new.html.erb
<h1>Добавить маршрут</h1>

<%= form_for(@train_route) do |f| %>
<% if @train_route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@train_route.errors.count, "error") %> prohibited this train_route from being saved:</h2>

      <ul>
        <% @train_route.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>

<div class="actions">
  <%= f.submit 'Создать' %>
</div>
<% end %>


<%= link_to 'Назад', train_routes_path %>