config/routes.rb
Rails.application.routes.draw do

  # Add for devise
  devise_for :users

  namespace :admin do
    resources :trains do
      resource :carriages, shallow: true
    end
    resources :railway_stations do
      patch :update_position, on: :member
    end
    resources :routes
    resources :carriages
    resources :tickets
  end

  resources :tickets
  resource :search, only: [:show, :create]


  get 'welcome/index'
  #root 'welcome#index'

  get  'searches/index'
  root 'searches#show'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/search.rb
class Search

  include ActiveModel::Model

  attr_accessor :start_station_id, :end_station_id
  attr_reader :result

  validates :start_station_id, :end_station_id, presence: true

  def start_station
    @start_station ||= RailwayStation.find(start_station_id)
  end

  def end_station
    @end_station ||= RailwayStation.find(end_station_id)
  end

  def run
    @result = Train.includes(route: :railway_stations).where(railway_stations: {id: start_station_id}) &
              Train.includes(route: :railway_stations).where(railway_stations: {id: end_station_id})
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @search ||= Search.new
  end

  def create
    @search = Search.new(search_params)
    @search.run
    render :show
  end

  protected

  def search_params
    params.require(:search).permit(:start_station_id, :end_station_id)
  end

end

app/views/searches/show.html.erb
<h1>Поиск билетов</h1>

<%= form_for(@search, method: :post, url: search_path) do |f| %>
    <%= render 'common/errors', resource: @search %>

      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <%# f.label :start_station_id, 'Станция отправления' %>
            <%= f.collection_select :start_station_id, RailwayStation.ordered_by_title.all, :id, :title, {}, class: 'form-control' %>
          </div>
          <div class="col-md-4">
            <%# f.label :end_station_id, 'Станция назначения' %>
            <%= f.collection_select :end_station_id, RailwayStation.ordered_by_title.all, :id, :title, {}, class: 'form-control' %>
          </div>
          <div class="col-md-4">
            <%= f.submit 'Найти', class: 'btn btn-primary' %>
          </div>
        </div>
      </div>

    <% if @search.result %>
        <% unless @search.result.empty? %>
            <h2><%= 'Результаты поиска:' %></h2>
            <table class="table table-hover">
              <thead>
              <tr>
                <td><%= 'Поезд' %></td>
                <td><%= 'Маршрут' %></td>
                <td><%= 'Время отправления' %></td>
                <td><%= 'Время прибытия' %></td>
              </tr>
              </thead>
              <tbody>
              <% @search.result.each do |t| %>
                  <tr>
                    <td><%= t.number %></td>
                    <td><%= t.route.title %></td>
                    <td><%= @search.start_station.arrival_time(t.route) %></td>
                    <td><%= @search.end_station.departure_time(t.route) %></td>
                    <td>
                      <%= form_tag new_ticket_path, method: :get do %>
                          <%= hidden_field_tag :train_id, t.id %>
                          <%= hidden_field_tag :start_station_id, @search.start_station_id %>
                          <%= hidden_field_tag :end_station_id, @search.end_station_id %>
                          <% submit_tag "Оформить", class: 'btn btn-success' %>
                      <% end %>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
        <% else %>
            <p><h4 class="text-danger">Ничего не найдено...</h4></p>
        <% end %>
    <% end %>
<% end %>

<% if user_signed_in? %>
    <p/><%= link_to 'Список купленных билетов', tickets_path, class: 'btn btn-link' %>
<% end %>