config/routes.rb
Rails.application.routes.draw do

  # Add for devise
  devise_for :users

  namespace :admin do
    resources :trains do
      resource :carriages, shallow: true
    end
    resources :railway_stations do
      patch :update_position, on: :member
    end
    resources :routes
    resources :carriages
    resources :tickets
  end

  resources :tickets
  resource :search, only: [:show, :create]


  get 'welcome/index'
  #root 'welcome#index'

  get  'searches/index'
  root 'searches#show'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :carriages

  validates :number, presence:  true

  def carr_by_type
    c_type = {}
    Carriage.carriage_types.each do |t|
      c_type[t] = 0
      self.carriages.each do |c|
        if c.carriage_type == t.to_s
          c_type[t] += 1
        end
      end
    end
    return c_type
  end

  def places_by_type (carriage_type)
    c_type = {"Верхние места" => 0, "Нижние места" => 0}
    # c_type = {}
    # c_type["Верхние места"] = 0
    # c_type["Нижние места"] = 0
    self.carriages.each do |c|
      if c.carriage_type == carriage_type
        if c.top_places_qty.present?
          c_type["Верхние места"] += c.top_places_qty
        end
        c_type["Нижние места"]  += c.bottom_places_qty unless c.bottom_places_qty.nil?
      end
    end
    return c_type
  end

  def carriage_list
    # Carriage.where(train_id: self.id).order(number: self.sort_order ? :asc : :desc)
    carriages.order(number: self.sort_order ? :asc : :desc)
  end

  def show_count_place_by_type(carriage_type, place_type)
    count = carriages.where(type: carriage_type).sum(place_type)
    count = 0 if count.nil?
  end

end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  def index
    @trains = Train.all
  end

  # GET /trains/1
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to admin_train_path(@train), notice: 'Поезд создан.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /trains/1
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to admin_trains_path(@train), notice: 'Информация по поезду успешно обновлена.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /trains/1
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to admin_trains_path, notice: 'Поезд успешно удален.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :current_station_id, :route_id, :sort_order, train_ids: [])
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_form.html.erb
<%= form_for [:admin, train] do |f| %>
    <%= render 'common/errors', resource: train %>

    <div class="col-md-6">
      <div>
        <%= f.label :number %>
        <%= f.text_field :number, class: "form-control" %><br/>
      </div>

      <div class="field">
        <%= f.label :current_station %>
        <%= f.collection_select :current_station_id, RailwayStation.all, :id, :title, {}, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :route %>
        <%= f.collection_select :route_id, Route.all, :id, :title, {}, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :sort_order %>
        <%= f.check_box :sort_order %>
      </div>
      <div class="'btn btn-success'">
        <%= f.submit 'Создать', class: 'btn btn-success' %>
      </div>
    </div>
<% end %>

app/views/admin/trains/_inline_edit_form.html.erb
<%= form_for [:admin, train], html: { style: "display: #{hidden ? 'none' : 'block'}"} do |f| %>
    <%= render 'common/errors', resource: train %>

    <div class="col-md-6">
      <div>
        <%= f.label :number %>
        <%= f.text_field :number, class: "form-control" %><br/>
      </div>
      <div class="'btn btn-success'">
        <%= f.submit  "#{train.new_record? ? 'Создать' : 'Изменить'}", class: 'btn btn-success'  %>
      </div>
    </div>
<% end %>

app/views/admin/trains/_train.html.erb
<div class="col-md-12">
  <table class="table table-striped">
    <tr>
      <td>
        <div id="train_title_<%= train.id %>">
          <%= train.number %>
        </div>
        <%= render 'inline_edit_form', train: train, hidden: true %>
      </td>
      <td><%= link_to 'Показать', admin_train_path(train), class: 'btn btn-link' %></td>
      <td><%= link_to 'Редактировать', '', class: 'btn btn-link edit-train-number', data: {train_id: train.id} %></td>
      <td><%= link_to 'Удалить', admin_train_path(train), method: :delete, data: {confirm: 'Вы уверены?'}, class: 'btn btn-link' %></td>
    </tr>
  </table>
</div>

app/views/admin/trains/edit.html.erb
<h1>Редактирование (поезд)</h1>
<%= render 'form', train: @train %>
<%= link_to 'Показать', admin_train_path(@train), class: 'btn btn-link' %> |
<%= link_to 'Назад', admin_trains_path, class: 'btn btn-link' %>

app/views/admin/trains/index.html.erb
<h1>Поезда</h1>
<table>
  <thead>
  <tr>
    <th>Номер</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <%= render @trains %>
  </tbody>
</table>
<br>
<%= link_to 'Создать поезд', new_admin_train_path, class: 'btn btn-link'  %>

app/views/admin/trains/new.html.erb
<h2>Новый поезд</h2>
<%= render 'form', train: @train %>
<%= link_to 'Назад', admin_trains_path, class: "btn btn-link" %>

app/views/admin/trains/show.html.erb
<h2>Информация о поезде</h2>

<p>
  <label>Поезд номер:</label>
  <%= @train.number %>
</p>

<p>
  <strong>Количество вагонов:</strong>
  <%= @train.carriages.length %>
</p>
<p>
  <strong>Список вагонов:</strong>
<ul>
  <% @train.carriage_list.each do |c| %>
      <li>
        <%= link_to "Вагон № #{c.number}", admin_carriage_path(c) %>
      </li>
  <% end %>
</ul>
</p>
<p>
  <strong>Количество вагонов по типам:</strong>
<ul>
  <% @train.carr_by_type.each do |t| %>
      <li>
        <%= "#{t[0]} -- #{t[1]} " %>
        <% @train.places_by_type(t[0]).each do |p| %>
            <%= "#{p[0]}: #{p[1]}" %>
        <% end %>
      </li>
  <% end %>
</ul>
</p>
<p>
  <strong>Маршрут:</strong>
  <% if @train.route.present? %>
      <%= @train.route.title %>
  <% else %>
      Маршрут не назначен
  <% end %>
</p>
<p>
  <strong>На станции:</strong>
  <% if @train.current_station.present? %>
      <%= @train.current_station.title %>
  <% else %>
      Не указано
  <% end %>
</p>
<p>
  <%= link_to 'Добавить вагон', new_admin_train_carriages_path(@train), class: "btn btn-success" %>
</p>
<%= link_to 'Редактировать', edit_admin_train_path(@train), class: "btn btn-link" %> |
<%= link_to 'Назад', admin_trains_path, class: "btn btn-link" %>